name: Main Build

on:
  workflow_dispatch:
  pull_request:
  push:
    branches: [ main ]

jobs:
  build:

    runs-on: windows-latest

    steps:

    - name: Checkout Juego.Samples
      uses: actions/checkout@v3
      with:
        path: Juego.Samples
        ref: main

    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 7.0.x
      
    - name: Build Juego.Samples
      run: dotnet build -c Release Juego.Samples/Source/Juego.Samples.sln